# Copyright (c) 2021, 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
---
name: Get or create an Oracle Cloud Infrastructure Registry (OCIR) repository
description: >-
  Create or return the URI and OCID for an existing Oracle Cloud Infrastructure Registry
  (OCIR) repository
inputs:
  compartment:
    description: >-
      OCID of the compartment in which to find or create the repository
    required: true
  name:
    description: Name of the repository to return or create
    required: true
outputs:
  repo_path:
    description: Full path to the repository including OCIR FQDN
  repo_ocid:
    description: The OCID of the repository
branding:
  icon: 'circle'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
